### ISSUE TITLE
BCDU_net_D1 BCDU_net_D3 differences

### ISSUE THREAD

**Issue by SouthAmericaB** [rezazad68/BCDU-Net#2]
Hi!
First of all, thank you very much for sharing your code.

Coud you tell me what is the difference between BCDU_net_D1 and BCDU_net_D3 networks?
I've tried to use BCDU_net_D3 but I have the next error:
OOM when allocating tensor with shape[2,5,256,256,64] 

Could you help me?
Thank you very much!

**Comment by rezazad68** [comment]
Hello, 
Thanks for the comment. 

About the BCDU_net_DN differences:
Please check the figure 1 in the paper. In the last part of the decoding section ( more clear in figure 2), the figure shows a dense connection between block 1, 2 .. N. It means that we can use N convolutional blocks here with a dense connection between them to capture more information. In the implementation, we only experimented with two types: N=1 (BCDU_net_D1) and N=3 (BCDU_net_D3). Thus, they only differ in dense section and D3 works better than D1.

About the OOM:
This error appears because you're running out of memory on GPU. Based on the image size (256), I think you are training on the Skin dataset. one possible way to solve this problem is to use a small image size. To do so, when preparing the dataset, resize them to 128*128. In this respect, open the "Prepare_ISIC2018.py" code and change:

height = 128
width  = 128

Run the whole code again. Let me know if you still have a problem with it. 

Best
